epochs: 1000
val_len: 0.2
test_len: 0.2
window: 72
stride: 72
lr_scheduler: magic
loss_fn: mse_loss
n_samples: 50
hidden_dim: 64
whiten_prob: [0.2]
batch_size: 32
batch_inference: 32
check_val_every_n_epoch: 10
covariate_dim: 11
spatial_dim: 1
diffusion_embedding_dim: 128
l2_reg: 0
lr: 0.001
batches_epoch: 1000
# load_from_pretrained: 'log/animal_movement/csdi/20240319T042645_70083570/epoch=479-step=688799.ckpt'
