epochs: 1000
val_len: 0.2
test_len: 0.2
window: 72
stride: 72
lr_scheduler: magic
loss_fn: mse_loss
n_samples: 50
whiten_prob: [0.2, 0.5, 0.8]
batch_size: 32
batch_inference: 32
check_val_every_n_epoch: 10
covariate_dim: 11
diffusion_embedding_dim: 128
l2_reg: 0
lr: 0.001
batches_epoch: 1000
# load_from_pretrained: 'log/animal_movement/csdi/20240319T192239_612893598/epoch=699-step=254099.ckpt'
# load_from_pretrained: 'log/animal_movement/csdi/20240320T043753_727102948/epoch=779-step=283139.ckpt'
# load_from_pretrained: 'log/animal_movement/csdi/20240321T231146_557701516/epoch=399-step=100799.ckpt'
# load_from_pretrained: 'log/animal_movement/csdi/20240328T034138_119757171/epoch=199-step=40599.ckpt'
load_from_pretrained: 'log/animal_movement/csdi/20240328T210044_354424313/epoch=269-step=52379.ckpt'