#### Dataset params ###########################################################
#dataset_name: [la_point, bay_point, la_bock, bay_bock, air, air36]
val_len: 0.2
test_len: 0.2

window: 72  # [24, 36]
stride: 72

#### Training params ##########################################################
whiten_prob: [0.2]
scale_target: False
epochs: 200
batch_size: 32
batch_inference: 32

loss_fn: l1_loss
lr_scheduler: magic
lr: 0.001
patience: 40
precision: 16
batches_epoch: 1000
check_val_every_n_epoch: 1
l2_reg: 0

### Model params #############################################################
u_size: 9
spatial_dim: 1
# load_from_pretrained: 'log/animal_movement/transformer/20240317T052357_27929863/epoch=80-step=56699.ckpt'
# load_from_pretrained: 'log/animal_movement/transformer/20240317T160305_125763804/epoch=90-step=63699.ckpt'
load_from_pretrained: 'log/animal_movement/transformer/20240317T202812_484482454/epoch=82-step=59593.ckpt'